### ISSUE TITLE
활성화

### ISSUE THREAD

**Issue by Kimyongwoo-cdf21a** [eca21b/HelpDesk#1]
org: eca21b

repo: eca21b-nmisp-Kimyongwoo-cdf21a

url: https://github.com/eca21b/eca21b-nmisp-Kimyongwoo-cdf21a

**Comment by kangwon-naver** [comment]
org: eca21b
repo: eca21b-nmisp-Kimyongwoo-cdf21a
Processing request above

**Comment by kangwon-naver** [comment]
org: eca21b
repo: eca21b-nmisp-Kimyongwoo-cdf21a
Success! Start your engine!
