### ISSUE TITLE
활성화 바랍니다.

### ISSUE THREAD

**Issue by kanghyun-eca21b** [eca21b/HelpDesk#3]
org: eca21b

repo: eca21b-00-00-00-kanghyun-eca21b

url: https://github.com/eca21b/eca21b-00-00-00-kanghyun-eca21b

**Comment by kangwon-naver** [comment]
org: eca21b
repo: eca21b-00-00-00-kanghyun-eca21b
Processing request above

**Comment by kangwon-naver** [comment]
org: eca21b
repo: eca21b-00-00-00-kanghyun-eca21b
Processing request above
